In [1]:
import os
from triangulator import create_triangulator_from_files

import sys
sys.path.append('../')
from utils.file_utils import create_capture_from_json

calibration_folder = '../calibration/calibration_data/'
intr_L = os.path.join(calibration_folder, 'calibration_L_frames=623_error=1.5265531081871597.pkl')
intr_R = os.path.join(calibration_folder, 'calibration_R_frames=624_error=0.99089142253755.pkl')
orientation_L = '../calibration/orientation_4.pkl'
orientation_R = '../calibration/orientation_2.pkl'

triangulator = create_triangulator_from_files(
    intr_files=[intr_L, intr_R],
    orientation_files=[orientation_L, orientation_R]
)

Image size is (1920, 1080)
Image size is (1920, 1080)


In [4]:
import numpy as np
actual_point = [0, 0, -150, 1]
zero_point_L = (592, 530)
zero_point_R = (558, 698)

point = (zero_point_L, zero_point_R)

projection = triangulator.projection_matrices[0]
cam_matr = triangulator.camera_matrices[0]

# get position with triangulators constructed projection matrix
position_proj = (projection @ actual_point)
position_proj = position_proj / position_proj[-1]
project_right = triangulator.projection_matrices[1] @ actual_point
project_right = project_right / project_right[-1]

print('position from projection matrix: ', position_proj)
print('position from right proj matrix: ', project_right)

print('triangulated zero point: ', triangulator.triangulate(point))

position from projection matrix:  [581.56786281 545.1872889    1.        ]
position from right proj matrix:  [555.18191316 713.1679173    1.        ]
homo:  [ 1.5706779   1.30009932 -1.86004661  1.        ]
triangulated zero point:  [ 1.5706779   1.30009932 -1.86004661]


In [3]:
A = triangulator.get_DLT_matrix(point)
print('A: \n', A)
U, S, Vt = np.linalg.svd(A, full_matrices=False)
print('s: \n', S)
print('Vt: \n', Vt)
vn = Vt[3, :]
print('vn: \n', vn.reshape((4, 1)))
print('vn normalized: \n', (vn / vn[-1]).reshape((4, 1)))
print('all close: ', np.allclose(U @ np.diag(S) @ Vt, A))
print('w2: ', vn.T @ A.T @ A @ vn)

# reproject
reproj = projection @ vn / vn[-1]
reproj = reproj / reproj[-1]
print('triangulated back: \n', reproj)

A: 
 [[-1.01306635e+02 -3.57856628e+02 -1.28197571e+03 -2.05908670e+05]
 [ 1.20121896e+03 -6.64431871e+02  8.13290341e+01  2.84906729e+03]
 [ 1.00089877e+03 -8.54792665e+01 -8.94926737e+02 -1.46734096e+05]
 [ 4.55432799e+02  1.26664041e+03  3.27338913e+02  4.67793424e+04]]
s: 
 [2.57155049e+05 1.58620795e+03 1.36583343e+03 2.86810560e+01]
Vt: 
 [[ 0.00153163 -0.00217146 -0.00621273 -0.99997717]
 [ 0.99601924 -0.0777372   0.04359569  0.00142352]
 [-0.07752572 -0.9969664  -0.00658851  0.00208711]
 [-0.04396701 -0.00319618  0.99900821 -0.00626711]]
vn: 
 [[-0.04396701]
 [-0.00319618]
 [ 0.99900821]
 [-0.00626711]]
vn normalized: 
 [[   7.01551484]
 [   0.50999278]
 [-159.40488786]
 [   1.        ]]
all close:  True
w2:  822.6029727326799
triangulated back: 
 [589.72687745 532.74620816   1.        ]


In [16]:
# Temuges DLT
point1 = zero_point_L
point2 = zero_point_R
P1 = triangulator.projection_matrices[0]
P2 = triangulator.projection_matrices[1]
A = [point1[1]*P1[2,:] - P1[1,:],
         P1[0,:] - point1[0]*P1[2,:],
         point2[1]*P2[2,:] - P2[1,:],
         P2[0,:] - point2[0]*P2[2,:]
        ]

A = np.array(A).reshape((4, 4))

print('Temuges: \n', A)

u, v = zero_point_L
p1, p2, p3 = tuple(P1)
print(v * p3 - p2)

B = A.transpose() @ A
U, S, Vh = np.linalg.svd(B, full_matrices=False)
# print('triangulated point: ')
# print(Vh[3, 0:3] / Vh[3, 3])

Temuges: 
 [[-1.01306635e+02 -3.57856628e+02 -1.28197571e+03 -2.05908670e+05]
 [ 1.20121896e+03 -6.64431871e+02  8.13290341e+01  2.84906729e+03]
 [ 1.00089877e+03 -8.54792665e+01 -8.94926737e+02 -1.46734096e+05]
 [ 4.55432799e+02  1.26664041e+03  3.27338913e+02  4.67793424e+04]]
[-1.01306635e+02 -3.57856628e+02 -1.28197571e+03 -2.05908670e+05]


In [20]:
p1, p2, p3 = tuple(triangulator.projection_matrices[0])
# print(p1)
# print(p2)
# print(p3)
print(triangulator.projection_matrices[0])

[[ 1.08309071e+03 -1.18985701e+03  2.28652066e+02  5.40099812e+05]
 [-2.12327677e+01 -1.33766810e+02  1.41676714e+03  7.01315580e+05]
 [-2.27765129e-01 -9.39106497e-01  2.57297559e-01  9.42790307e+02]]


In [ ]:
caps = [
    create_capture_from_json(4, '../config/capture_params.json'),
    create_capture_from_json(2, '../config/capture_params.json')
]

In [1]:
import cv2


while True:
    idx = 0
    for cap in caps:
        ret, frame = cap.read()

        if not ret:
            break

        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        corners, ids, _ = cv2.aruco.detectMarkers(
            image=gray,
            dictionary=cv2.aruco.getPredefinedDictionary(cv2.aruco.DICT_4X4_50)
        )
        if ids is not None and 0 in ids:
            for corner_idx in range(len(ids)):
                if ids[corner_idx] == 0:
                    cv2.aruco.drawDetectedMarkers(
                        frame, 
                        corners=corners, 
                        ids=ids
                        )
                    break
        idx += 1
        cv2.imshow(f'cam{idx}', cv2.resize(src=frame, dsize=None, fx=0.35, fy=0.35))
    if cv2.waitKey(10) == 27:
        break


cv2.imshow('huh', frame)
cv2.waitKey(1000)
cv2.destroyAllWindows()

NameError: name 'caps' is not defined

In [48]:
for cap in caps:
    cap.release()

cv2.destroyAllWindows()